common/urls.py
from django.urls import path
from . import views


app_name = 'common' # for redirection purpose

urlpatterns=[
    
    path('',views.home,name='home'),
    path('common_admin',views.admin, name='admin_login'),
    path('common_custlog',views.customer_login ,name='customer_login'),
    path('common_custsig',views.customer_signup, name='customer_signup'),
    path('common_sellerlog',views.seller_login,name='seller_login'),
    path('common_sellersig',views.seller_signup,name='seller_signup'),
    
]

customer/urls.py
from django.urls import path
from . import views




urlpatterns=[
    path('customer_home',views.cust_home),
    path('customer_mycart',views.cust_cart),
    path('customer_cart',views.cust_carts),
    path('customer_products',views.cust_product),
    path('customer_profits',views.cust_profit),
     path('customer_changes',views.cust_change),
     path('customer_css',views.cust_css),
     path('customer_cssbox',views.cust_cssbox),
    path('customer_csspro',views.cust_csspro),
    path('customer_csspos',views.cust_csspos),
    path('customer_csssticky',views.cust_csssticky),
    path('customer_cssflexbox',views.cust_csssflexbox),
    path('customer_cssgrid',views.cust_csssgrid),
      
    
    
]

ecomadmin/urls.py
from django.urls import path,include
from . import views




urlpatterns=[
    path('admin_home',views.admin_home),
    path('approve_sell',views.approve_sell),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/',include('customer.urls')),
    path('',include('common.urls')),
    path('seller/',include('seller.urls')),
    path('ecomadmin/',include('ecomadmin.urls'))
    
]

seller/urls.py
from django.urls import path,include
from . import views




urlpatterns=[
    path('sellers_home',views.seller_home),
    path('add_product',views.add_product),
     path(' profit',views. profit),
      path('changeproduct',views.changeproduct),
]

common/models.py
from django.db import models

# Create your models here.

customer/models.py
from django.db import models

# Create your models here.

ecomadmin/models.py
from django.db import models

# Create your models here.

seller/models.py
from django.db import models

# Create your models here.

common/views.py
from django.shortcuts import render

# Create your views here.


def admin(request):
    return render(request,'common/admin_login.html')
    
def customer_login(request):
    return render(request,'common/customer_login.html')  

def customer_signup(request):
     return render(request,'common/customer_signup.html')         

def home(request):
     return render(request,'common/projecthome.html')   

def seller_login(request):
     return render(request,'common/sellerlog.html')         

def seller_signup(request):
     return render(request,'common/sellersig.html')              

customer/views.py
from django.shortcuts import render

# Create your views here.
def cust_home(request):
    return render(request,'customer/home.html')
    
def cust_cart(request):
    return render(request,'customer/mycart.html')  

def cust_carts(request):
     return render(request,'customer/cart.html')         

def cust_product(request):
     return render(request,'customer/product_details.html')   

def cust_profit(request):
     return render(request,'customer/profit.html')         

def cust_change(request):
     return render(request,'customer/change.html')  
                 
def cust_css(request):
     return render(request,'customer/css.html')              
       
def cust_cssbox(request):
     return render(request,'customer/cssbox.html')              

def cust_csspro(request):
     return render(request,'customer/csspro.html')            

def cust_csspos(request):
     return render(request,'customer/position_relation.html')                 

def cust_csssticky(request):
     return render(request,'customer/positionsticky.html')

def cust_csssflexbox(request):
     return render(request,'customer/css_flexbox.html')                     

def cust_csssgrid(request):
     return render(request,'customer/cssgrid.html')                     

ecomadmin/views.py
from django.shortcuts import render

# Create your views here.


def admin_home(request):
    return render(request,'ecomadmin/home.html')



def approve_sell(request):
    return render(request,'ecomadmin/approve_seller.html')

seller/views.py
from django.shortcuts import render

# Create your views here.

def seller_home(request):
    return render(request,'seller/home.html')



def add_product(request):
    return render(request,'seller/add_product.html')



def profit(request):
    return render(request,'seller/profit.html')


def changeproduct(request):
    return render(request,'seller/change_product.html')

common/templates/common/admin_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>admin login</h1>
</body>
</html>

common/templates/common/customer_login.html
{% extends 'common\master.html' %}
{% block content %}
<body>
   
    
    <table align="center" border="1px" width="60%" height="50%" style="color:aqua"><form action="">
        <tr>
            <td colspan="2" align="center">
            <h1>login</h1>
        </td>
        </tr>
        <tr>
            <td width="30%"> <label for=""> user name:</label></td>
            <td width="80%"><input type="text" placeholder="enter your name" size="15" maxlenght="15"> </td>
                       
        </tr>
        <tr>
            <td width="30%"> <label for=""> passward:</label></td>
            <td width="80%"><input type="password" size="15" maxlenght="15"> </td>
                       
        </tr>
        <tr>
            <td width="30%">
                <input type="submit">

        </tr>
        <tr>
            <td align="center" colspan="2"> <a href="{% url 'common:customer_signup' %}">already exit account</a></td>
        </tr>
    </form>

    </table>
    </body>

   
    {% endblock %}

common/templates/common/customer_signup.html
{% extends 'common\master.html' %}
{% block content %}

<body>
    <table align="center" border="1px" width="60%" height="50%" style="color:aqua"><form action="">
        <tr>
            <td colspan="2" align="center">
            <h1>FROM</h1>
        </td>
        </tr>
        <tr>
            <td width="30%"> <label for="">  name:</label></td>
            <td width="80%"><input type="text" placeholder="enter your name" size="15" maxlenght="15"> </td>
                       
        </tr>
        <tr>
            <td width="30%"> <label for=""> email id:</label></td>
            <td width="80%"><input type="email" size="15" maxlenght="15"> </td>
                       
        </tr>
        <tr>
            <td width="30%"> <label for=""> phone number:</label></td>
            <td width="80%"><input type="phone" size="15" maxlenght="15"> </td>
                       
        </tr>
       
        <tr>
            <td width="30%">
                <input type="submit">
    
        </tr>
        <tr>
            <td align="center" colspan="2"> <a href="{% url 'common:customer_login' %}">signin</a></td>
        </tr>
    </form>
    
    </table>
    
    </body>

{% endblock %}

common/templates/common/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
        <nav style="background: rgb(131, 173, 201);">
        
    <a href="{% url 'common:admin_login' %}">Admin login</a>
    <a href="{% url 'common:customer_login' %}">Customer login</a>
    <a href="{% url 'common:customer_signup' %}">Seller Login</a>

        </nav>
    <div>
        {% block content %}
        {% endblock %}
    </div>
    <div>
        <footer>
            <li>happy </li>

        </footer>
    </div>
</body>
</html>

common/templates/common/projecthome.html
{% extends 'common/master.html' %}
{% load static %}

 
{% block content %}
    
    <img src="{% static 'images/lap.jpg' %}" height="200px" alt="">
 
    {% endblock %}

common/templates/common/seller_login.html
{% extends 'common/master.html' %}
{% load static %}
     

{% block content %}

<img src="{% static 'images/lap.jpg' %}" height="200px" alt="">
 
{% endblock %}

common/templates/common/seller_signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>seller signup</h1>
</body>
</html>

customer/templates/customer/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h1>cart</h1>
</body>
</html>

customer/templates/customer/change.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>change password</h1>
</body>
</html>

customer/templates/customer/css_flexbox.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>css flexbox</title>
    <style>
        body{
            margin: 0;
        }
        h1{
            margin: 0;
            color: white;
        }
        .container{
            background-color: aqua;
            display: flex;
            height: 400px;
            /* flex-direction: column; */
            /* flex-direction: row-reverse; */
            justify-content: center;
            /* justify-content: flex-end; */
            /* justify-content: space-between; */
            /* justify-content: space-around; */
            /* justify-content: space-evenly; */
            align-items: center;
            /* align-items: flex-end; */
            flex-wrap: wrap;

        }
        .one,.two,.three{
            width: 300px;
            height: 200px;
            background-color: blue;
            border: 1px solid white;
            text-align: center;
            padding: 5px;
        }
        .one{
            order: 3;
        }
        .two{
            order: 1;
        }
        .three{
            order: 2;
        }
    </style>
</head>
<body>
    <div class="container" >
        <div class="one">
            <h1>section1</h1>
        </div>
        <div class="two">
            <h1>section2</h1>
        </div>
        <div class="three">
            <h1>section3</h1>
        </div>
    </div>


    
</body>
</html>

customer/templates/customer/cssbox.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>box model</title>
    <link rel="stylesheet" href="{% static 'css/cssbox.css'%}">
    <style>
        h1{
    background-color: blue;
    color: black;
   /* margin: 50px;
    padding: 50px;
    margin: 20px 50px 150px 300px;
    margin: 50px 500px;*/
    margin-top: 100px;
    margin-left: 300px;
    margin-right: 159px;
    border:3px solid black;
    padding-top: 200px;
    padding-left: 300px;
}
    </style>
</head>
<body>
    <h1>css box</h1>
    
</body>
</html>

customer/templates/customer/cssgrid.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>grid</title>
    <style>
        .container{
            background-color: blueviolet;
            display: grid;
            grid-template-columns: auto auto auto;
            grid-template-rows: auto auto;
            grid-gap: 20px 5px;
            padding: 20px;
        }
        .container div{
            padding: 10px;
        }
        .item{
            background-color: antiquewhite;
            border: 1px solid red;
            height: 200px;
        }

    </style>
</head>
<body>
    <div class="container">
        <div class="item">1</div>
        <div class="item">2</div>
        <div class="item">3</div>
        <div class="item">4</div>
        <div class="item">5</div>
        <div class="item">6</div>
    </div>
</body>
</html>

customer/templates/customer/csspro.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>css properties</title>
    <link rel="stylesheet" href="{% static 'css/csspro.css' %}">
    <style>
       /* color properties*/
        h1{
            color:brown;
            /*visibility: hidden;*/
            display: none;

        }
        h2{
            color:#395943;
        }
        h3{
            color:rgb(120, 26, 99);
   
        }
        p{
            color:rgba(15, 43, 146, 0.6);
        }

        /*background properties*/
        body{
            height:fit-content;
           /* background-image: url("https://picsum.photos/id/1/200/300");*/
          /*    background-repeat: no-repeat; */
          /*background-repeat: repeat-x;*/
           /*background-repeat: repeat-y;;*/
          /* background-repeat: no-repeat;
           background-position: right top;
           background-size: cover;*/
        }
        /*font and text properties*/

        p{
            font-size:50px;
            font-style: italic;
            font-family: Arial, Helvetica, sans-serif;
            font-weight: bolder;
            text-align: center;
            text-decoration:underline;
            text-transform: uppercase;
        }
        marquee{
            color:blue;
        }
        /*overflow*/
        #overflow{
            height: 150px;
            width: 200px;
            border:5px solid blueviolet;
            background-color: blue;
            color:bisque;
        
            overflow: scroll;
            overflow:auto;
            box-shadow: 20px 40px 60px 20px royalblue;
            margin-bottom: 100px;
        }
        a:visited{
            color: #395943;
        }
        
        a:hover{
            color:blue;
        }
        input:focus{
            color:rgb(64, 0, 255);
        }
        input::placeholder{
            color: aqua;
        }
        h2::first-letter{
            color:red;
        }

    </style>
</head>

<body>
    <h1>css properties</h1>
    <h2>css</h2>
    <h3>java</h3>
    <p>
        <marquee behavour="alternate" direction="left">Lorem ipsum dolor sit amet.</marquee>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores velit eligendi alias aliquid praesentium
        dolore.</p>
        <a href="#">Lorem,ipsum</a>
        <input type="text" placeholder="enter your name">
        <div id="overflow">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam ullam, aperiam sit id a et voluptatibus nemo esse libero! Hic consectetur sed qui nesciunt. Libero nostrum harum expedita, cupiditate consequatur ex aut aliquam. Ipsam, nesciunt, illum quo tempora enim blanditiis ex distinctio voluptas sunt obcaecati, ducimus repudiandae pariatur amet et.
        </div>


</body>

</html>

customer/templates/customer/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>home</h1>
   
</body>
</html>

customer/templates/customer/mycart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>welcome to cart</p>
</body>
</html>

customer/templates/customer/position_relation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/csspos.css' %}">
    <style>
        /*position_relation*/
        /* #parent{
            height: 500px;
            width: 500px;
            background-color: yellow;
        }
        .red{
            height: 100px;
            width: 100px;
            background-color:red;
        }

        .blue{
            height: 100px;
            width: 100px;
            position:relative;
            left:20px;
            top: 20px
            background-color:blue;
            
        }

        .green{
            height: 100px;
            width: 100px;
            background-color:green;

        } */
        /* positionn absolute*/

        /*  #parent{
            height: 500px;
            width: 500px;
            position: relative;
            background-color: yellow;
        }
        .red{
            height: 100px;
            width: 100px;
            background-color:red;
        }

        .blue{
            height: 100px;
            width: 100px;
            position:absolute;
            left:20px;
            bottom:0;
            background-color:blue;
            
        }

        .green{
            height: 100px;
            width: 100px;
            background-color:green;

        }*/




        /*position fixed*/
        #parent {
            height: 500px;
            width: 500px;
            position: relative;
            background-color: yellow;
        }

        .red {
            height: 100px;
            width: 100px;
            background-color: red;
        }

        .blue {
            height: 100px;
            width: 100px;
            position: fixed;
            right: 50px;
            bottom: 50px;
            background-color: blue;

        }

        .green {
            height: 100px;
            width: 100px;
            background-color: green;

        }
    </style>
</head>

<body>
    <div id="parent">
        
        <div class="red"></div>
        <div class="blue"></div>
        <div class="green"></div>

    </div>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati dolore eius totam facilis. Sapiente cumque
        eius facilis odit aspernatur eveniet obcaecati tenetur laborum esse rem? Obcaecati, voluptatem amet? Ullam
        in iure debitis ad necessitatibus eos ipsum quis tempora esse odit, praesentium officia nam earum velit
        inventore cum illo id quo. Dolores vero odit maxime aliquam eum. Itaque nulla cum molestias quam. Possimus
        dicta nam illo deleniti suscipit laudantium sunt debitis rerum voluptatum fuga? Molestias nesciunt enim cum
        repellat est magni sed iure deserunt, praesentium hic pariatur voluptate fuga quos tenetur tempore obcaecati
        ducimus perspiciatis reprehenderit ipsa inventore accusamus suscipit sit qui quia. Velit sequi reiciendis
        eum nisi, non quod quis officiis dicta iste sed modi mollitia consequatur animi, voluptatem sit cum eius
        repudiandae laboriosam explicabo maiores. Fugit, laboriosam quae? Asperiores, odit. Tempore eveniet sit,
        quidem ducimus animi ipsum doloremque beatae enim qui, reiciendis minima eum ullam harum corrupti id,
        suscipit consequuntur maxime. Voluptate facere exercitationem enim, repellendus expedita, eligendi mollitia
        beatae, suscipit ab optio velit odio repudiandae consequatur reiciendis! Voluptatibus a soluta ipsam vel
        cumque velit, repudiandae corporis dolor deleniti ab obcaecati earum ut tenetur fugit autem asperiores non
        nobis. Inventore, nihil sit alias repellendus ad consectetur dolor debitis accusamus pariatur rem impedit
        maiores cupiditate earum. Illo ullam nulla, culpa odio temporibus sapiente minus, distinctio esse dolor at
        perferendis deserunt perspiciatis, amet incidunt reiciendis exercitationem. Iste unde soluta sit itaque
        inventore alias ad, harum provident ab fugiat veniam repellat voluptatum cumque, nam exercitationem, minus
        placeat cupiditate maiores modi nostrum deserunt illo. Ad nemo dolorem voluptates quis incidunt veritatis
        magnam reiciendis quae hic. Sequi rem voluptatum eum amet est a perferendis nemo, minima similique quam.
        Nemo veritatis nam mollitia tenetur omnis ea officiis veniam dolores labore, id, quam aut repellat a
        laboriosam similique, suscipit illo porro quidem eum temporibus. Quam accusantium consequatur, dignissimos,
        enim ducimus voluptates ratione neque quas iusto natus nemo explicabo nostrum ex. Adipisci explicabo
        expedita vero doloribus ipsa totam? Cum, beatae? Adipisci maiores at sapiente. Sint hic eligendi nisi vero?
        Autem ad aspernatur voluptatum itaque rerum repellendus id? Sed fuga esse odio nisi ad, eum atque deleniti,
        assumenda accusamus iusto quis dolorum, eos delectus eius consectetur vel vitae dignissimos quisquam unde
        alias tenetur. Ex magni cumque reiciendis velit voluptate explicabo dolorum? Aspernatur quibusdam dolore
        ducimus harum vel molestiae, alias, quas sit, eaque quia incidunt deserunt numquam sed labore modi cum et
        nihil voluptatum. Doloremque tenetur officiis recusandae voluptas, impedit numquam esse nam explicabo dolor.
        Nesciunt voluptatibus eos veritatis quaerat, vero illum id illo nulla atque! Dignissimos nobis dolorem,
        magni deserunt tenetur incidunt temporibus voluptatibus nemo facilis quam eum aperiam sequi! Laboriosam
        molestias reprehenderit doloribus asperiores fugit consequatur alias amet hic doloremque voluptatum, magni
        totam saepe eveniet possimus nihil earum architecto perferendis non cum. Non dolor est ipsum nobis eos atque
        libero voluptates fugiat debitis maiores! Mollitia quo ipsum neque nam voluptatum sed odio corrupti
        accusamus veritatis quos. Mollitia ducimus praesentium expedita consequatur veniam dolorum aliquid, iure
        porro doloremque exercitationem ratione sapiente eum debitis odio aliquam, officiis ea pariatur quo commodi
        fugiat, quos tempore quaerat magnam? Vero voluptatum ipsam iure quas ut magni iusto. Possimus laudantium
        temporibus alias ducimus, error excepturi debitis impedit esse laboriosam veniam ipsa repudiandae modi
        quidem! Sapiente temporibus quod dolores, iusto amet a maxime omnis! Quam quia culpa corporis vel voluptatum
        quaerat earum blanditiis doloribus iure minima enim quasi sapiente voluptates odio, harum quae cum illo, non
        a aperiam alias ex! Provident harum, placeat quasi quod distinctio maxime ab temporibus delectus, beatae
        esse necessitatibus vero rem. Hic, totam voluptatem quod voluptates tempore pariatur odio ut non quasi ab
        voluptas optio neque tenetur fugiat? Reiciendis distinctio quibusdam dolorem ea impedit architecto
        temporibus nulla ut repellendus optio! Perferendis optio sapiente dolor, quisquam ratione in deserunt cum
        voluptas, placeat nisi tempora blanditiis quia. Facere quod fugit ut unde deleniti tempora illo, asperiores
        commodi animi ipsa. Eveniet quaerat voluptates adipisci blanditiis cumque et in eos quasi provident,
        accusantium deserunt natus distinctio debitis, voluptas aliquid. Provident sapiente laudantium repudiandae
        tempore consequuntur eaque explicabo commodi error fuga, saepe dolorum ipsam nisi dolore tenetur nulla
        placeat quod ea quae facilis ad dolor amet, voluptas voluptatum earum! Impedit, explicabo ratione. Ipsum
        iste adipisci perferendis recusandae quibusdam veniam autem incidunt, nisi repudiandae exercitationem, optio
        animi repellat rem! Delectus doloribus minima at placeat, exercitationem quam nihil? Animi magnam aut cum
        fugit odio necessitatibus nam at cumque commodi sint ea molestias enim debitis, rerum, ex facere porro
        maxime minus? Praesentium fugit porro natus at rerum repellat impedit voluptates cumque nesciunt atque esse
        nam, illum corrupti perspiciatis? Veritatis delectus odit at cumque, incidunt quas dolore harum eius dicta
        tenetur asperiores dignissimos, ea atque sed minima laudantium possimus officiis fugit quam, necessitatibus
        totam. Possimus ullam quod quibusdam magni rem incidunt aperiam nesciunt perspiciatis rerum, nihil culpa ex
        odit alias, facere libero tempore optio commodi? Numquam perspiciatis nemo quam in voluptatem mollitia
        blanditiis! Similique fuga voluptatem eos provident sit cumque molestias et dolorem asperiores quas numquam
        aliquid, reprehenderit illo natus harum officia at nesciunt error dolores quo modi eius vel neque. Nostrum
        necessitatibus ullam at! Quia, voluptatibus. Vitae ducimus nam doloribus error, quibusdam repellendus quo
        voluptate reiciendis necessitatibus omnis at quia hic ipsam adipisci consequatur cum voluptates repudiandae
        ex. Fugiat inventore laborum nam, voluptates maxime neque mollitia. Vitae, quam. Tempore iure dolores
        incidunt repellendus, fuga veritatis cupiditate placeat libero veniam ipsam ratione quo adipisci
        voluptatibus quae ducimus dolore, deleniti delectus exercitationem aspernatur voluptatem eveniet corrupti
        hic? Exercitationem ipsum laboriosam culpa tempore? Aspernatur ut facilis laborum aliquam nostrum earum
        inventore blanditiis a reiciendis consequatur? Delectus tenetur, amet aut quibusdam nesciunt reprehenderit
        repudiandae quo officiis pariatur laborum quidem veniam qui suscipit in ex sint perferendis possimus officia
        voluptas perspiciatis. Consequuntur mollitia eaque distinctio illum consequatur ad cum quia eum quas vitae
        reprehenderit, amet corrupti et, modi vero rem laborum, non earum eos itaque nesciunt? Porro, iusto magni
        nam aspernatur fugiat facilis ipsum ipsam, assumenda quos quod laborum repellat at, aliquam cumque voluptas
        vel nemo veritatis similique hic corrupti iste sunt mollitia ad voluptatum? Sequi ad nesciunt doloremque
        sint facere architecto repellat.</p>

</body>

</html>

customer/templates/customer/product_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>product details </h1>
</body>
</html>

customer/templates/customer/profit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>profit</h1>
</body>
</html>

ecomadmin/templates/ecomadmin/approve_seller.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>approve seller</h1>
</body>
</html>

ecomadmin/templates/ecomadmin/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>home</h1>
    <img src="{% static 'images/ac.jpg' %}">
</body>
</html>